# Generated by Django 4.1.7 on 2023-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_requests_history_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests_history',
            name='data',
            field=models.JSONField(),
        ),
    ]
