# Generated by Django 4.1.7 on 2023-03-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_requests_history_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests_history',
            new_name='Room',
        ),
    ]
